"""Reusable LLM research primitives."""

from . import extract_answer, extract_hiddens, families, inference, prompt, steering
from .choice import ChoiceSet, VariantRule, build_letter_token_ids, compute_letter_log_probs
from .extract_answer.parsing import (
    coerce_llm_float,
    extract_balanced_json,
    from_choice_set,
    looks_like_terminal_verdict,
    parse_json_array_with_repair,
    parse_json_with_repair,
    strip_fences,
    strip_thinking,
    terminal_fragment,
)
from .extract_answer.terminal import TerminalFragment
from .extract_hiddens.capture import CaptureMode, CaptureSpec, HiddenCapture
from .extract_hiddens.locator import BoundaryPlan, find_subsequence, nonpad_last_positions, positions_from_spans, span_positions
from .extract_hiddens.pooling import PoolMode, pool_for, pool_layered, pool_span, pool_spans
from .families import ModelFamily, all_families, identify_family
from .inference import BudgetSpec, InferenceResult, SamplingConfig, ScoringSpec, generate as runtime_generate
from .inference.batch import JobManifest, RequestRecord, collect_ordered_results
from .inference.execution import forward_hidden_only, forward_query_logits, forward_selected_logits
from .forward import (
    CaptureSpec as ForwardCaptureSpec,
    ForwardResult,
    ForwardSpec,
    Intervention,
    InterventionContext,
    OutputSpec,
    add,
    forward,
    norm_match,
    patch,
    subspace_subtract,
)
from .hooks_runtime import (
    HookMode,
    WriteHookContext,
    extract_layerwise_at_positions,
    hidden_hooks_context,
    register_hidden_hooks,
    subspace_subtract_hook,
)
from .mask import (
    TokenContext,
    TokenMask,
    apply_loss_mask,
    at,
    at_positions,
    between_tags,
    in_char_range,
    in_span,
    last_n,
    matches,
    not_thinking,
    role,
)
from .prompt.template import assistant_header, locate_message
from .prompt.tokenize import build_token_context, find_subsequences, tokenize_with_loss_mask
from ruff_cm.configs.thinking import ThinkingConfig, resolve_thinking
from .steering import ActivationPatcher, NormMatchedSteer, SubspaceMeanSub, fit_subspace_basis
from .trajectory import (
    Segment,
    TokenSpan,
    Trajectory,
    TrajectoryParser,
    chat_template_parser,
    combined,
    select_hiddens,
    select_logits,
    select_steps,
    step_parser,
    thinking_parser,
)

__all__ = [
    "BoundaryPlan",
    "BudgetSpec",
    "CaptureMode",
    "CaptureSpec",
    "ChoiceSet",
    "ActivationPatcher",
    "ForwardCaptureSpec",
    "ForwardResult",
    "ForwardSpec",
    "HiddenCapture",
    "HookMode",
    "InferenceResult",
    "Intervention",
    "InterventionContext",
    "JobManifest",
    "ModelFamily",
    "NormMatchedSteer",
    "OutputSpec",
    "PoolMode",
    "RequestRecord",
    "SamplingConfig",
    "ScoringSpec",
    "Segment",
    "SubspaceMeanSub",
    "TerminalFragment",
    "ThinkingConfig",
    "TokenContext",
    "TokenMask",
    "TokenSpan",
    "Trajectory",
    "TrajectoryParser",
    "VariantRule",
    "WriteHookContext",
    "add",
    "all_families",
    "apply_loss_mask",
    "assistant_header",
    "at",
    "at_positions",
    "between_tags",
    "build_token_context",
    "build_letter_token_ids",
    "chat_template_parser",
    "coerce_llm_float",
    "collect_ordered_results",
    "compute_letter_log_probs",
    "combined",
    "extract_answer",
    "extract_balanced_json",
    "extract_layerwise_at_positions",
    "extract_hiddens",
    "families",
    "fit_subspace_basis",
    "find_subsequence",
    "find_subsequences",
    "forward",
    "forward_hidden_only",
    "forward_query_logits",
    "forward_selected_logits",
    "from_choice_set",
    "hidden_hooks_context",
    "identify_family",
    "in_char_range",
    "in_span",
    "last_n",
    "locate_message",
    "looks_like_terminal_verdict",
    "matches",
    "not_thinking",
    "nonpad_last_positions",
    "norm_match",
    "parse_json_array_with_repair",
    "parse_json_with_repair",
    "patch",
    "positions_from_spans",
    "pool_for",
    "pool_layered",
    "pool_span",
    "pool_spans",
    "inference",
    "prompt",
    "register_hidden_hooks",
    "resolve_thinking",
    "role",
    "runtime_generate",
    "select_hiddens",
    "select_logits",
    "select_steps",
    "span_positions",
    "step_parser",
    "steering",
    "strip_fences",
    "strip_thinking",
    "subspace_subtract",
    "subspace_subtract_hook",
    "terminal_fragment",
    "thinking_parser",
    "tokenize_with_loss_mask",
]
