from __future__ import annotations

from pathlib import Path
from typing import Protocol


class Logger(Protocol):
    def log(self, metrics: dict, *, step: int | None = None) -> None: ...

    def set_summary(self, metrics: dict) -> None: ...

    def record_ckpt(self, ckpt_path: Path, *, extras: dict | None = None) -> None: ...

    def get_ckpt(self) -> Path | None: ...

    def hf_report_to(self) -> list[str]: ...

    def hf_callbacks(self) -> list: ...

    def finish(self) -> None: ...
