"""Quantitative analysis helpers for statistics, plotting, probes, and geometry."""

from .behavioral import (
    auto_monotonicity_score,
    cohens_kappa,
    compute_sdt,
    expected_calibration_error,
    meta_d_prime,
    monotonicity_score,
    progress_drop_score,
)
from .geometry import (
    compute_pairwise_cosine_similarity,
    compute_rdm_layers,
    compute_rule_axis,
    linear_cka,
    orthogonal_procrustes,
    safe_normalize,
    subspace_angles,
)
from .probe import (
    ProbesByLayerResult,
    LinearLayerFitCache,
    LinearProbe,
    LogisticProbe,
    PCAScorer,
    TorchLogisticRegression,
    build_linear_layer_fit_cache,
    load_classifiers,
    load_clf_dispatch,
    make_classifier,
    save_classifiers,
    train_probes_per_layer,
)
from .stats import batched_spearmanr, format_pvalue, mean_ci, mean_sem, smooth_curve_ci

__all__ = [
    "ProbesByLayerResult",
    "LinearLayerFitCache",
    "LinearProbe",
    "LogisticProbe",
    "PCAScorer",
    "TorchLogisticRegression",
    "auto_monotonicity_score",
    "build_linear_layer_fit_cache",
    "batched_spearmanr",
    "cohens_kappa",
    "compute_pairwise_cosine_similarity",
    "compute_rdm_layers",
    "compute_rule_axis",
    "compute_sdt",
    "expected_calibration_error",
    "format_pvalue",
    "linear_cka",
    "load_classifiers",
    "load_clf_dispatch",
    "make_classifier",
    "mean_ci",
    "mean_sem",
    "meta_d_prime",
    "monotonicity_score",
    "orthogonal_procrustes",
    "progress_drop_score",
    "safe_normalize",
    "save_classifiers",
    "smooth_curve_ci",
    "subspace_angles",
    "train_probes_per_layer",
]
